spring.application.name=be11

# DB
# spring.datasource.url=jdbc:oracle:thin:@yummy_tp?TNS_ADMIN=C:/Wallet_yummy
# spring.datasource.username=admin
# spring.datasource.password=OracleCloud123
# spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Otro
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ;alua
spring.thymeleaf.check-template-location=false

# configuracion H2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always

#secret key del jwt
jwt.secret=EstaEsUnaClaveMuyLargaYSeguraParaJWTTokenDePrueba
